package com.example.demosqltest.jpa.additional.transaction.service;

import com.example.demosqltest.jpa.additional.transaction.entity.HomeEntityAutoGeneratedId;
import com.example.demosqltest.jpa.additional.transaction.repository.HomeWithAutoGeneratedIdRepository;
import com.example.demosqltest.jpa.entity.HomeEntity;
import com.example.demosqltest.jpa.repositories.HomeRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import javax.transaction.Transactional;

@Service
@RequiredArgsConstructor
public class ServiceWithInnerRequiredNewTransaction {

    public static final String NESTED_TRANSACTION = "nested-transaction";
    private final HomeRepository homeRepository;
    private final HomeWithAutoGeneratedIdRepository homeWithAutoGeneratedIdRepository;

    @Transactional(Transactional.TxType.REQUIRES_NEW)
    public void nestedThatThrow(String name, Long id) {
        HomeEntity homeEntity = new HomeEntity();
        homeEntity.setId(id);
        homeEntity.setName(name + NESTED_TRANSACTION);
        homeEntity.setIsNew(true);
        homeRepository.saveAndFlush(homeEntity);

    }



    @Transactional(Transactional.TxType.REQUIRES_NEW)
    public void nestedTransactionWithAutoGenerated(String name, Long id) {
        HomeEntityAutoGeneratedId homeEntity = new HomeEntityAutoGeneratedId();
        homeEntity.setId(id);
        homeEntity.setName(name + NESTED_TRANSACTION);
        homeEntity.setIsNew(true);
        homeWithAutoGeneratedIdRepository.saveAndFlush(homeEntity);
    }




    @javax.transaction.Transactional(javax.transaction.Transactional.TxType.REQUIRES_NEW)
    public HomeEntity saveInSeparateTransaction(String namePrefix) {
        HomeEntity homeEntity = new HomeEntity();
        homeEntity.setName(namePrefix+ ServiceWithOuterTransaction.TRANSACTION);
        homeEntity.setId(1L);// В случае если нет @GeneratedAuto
        homeRepository.saveAndFlush(homeEntity);
        return homeEntity;
    }
}
