package com.example.demosqltest.jpa.additional.transaction.repository;

import com.example.demosqltest.jpa.additional.transaction.entity.HomeEntityAutoGeneratedId;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.Collection;
import java.util.Optional;


public interface HomeWithAutoGeneratedIdRepository extends JpaRepository<HomeEntityAutoGeneratedId, Long> {
    @Query("select he.id as id , he.name as name " +
            "from HomeEntityAutoGeneratedId he " +
            "where (he.id = :id and he.name <> :name) or (he.id <> :id and he.name = :name)")
    Optional<HomeEntityAutoGeneratedId> findByDisjointFailed(@Param("id") Long id, @Param("name") String name);

    Collection<HomeEntityAutoGeneratedId> findAllByName(String name);
}
