package com.example.demosqltest.jpa.additional.transaction.commit;

import com.example.demosqltest.jpa.entity.HomeEntity;
import com.example.demosqltest.jpa.repositories.HomeRepository;
import com.example.demosqltest.jpa.additional.transaction.entity.HomeEntityAutoGeneratedId;
import com.example.demosqltest.jpa.additional.transaction.repository.HomeWithAutoGeneratedIdRepository;
import com.example.demosqltest.jpa.additional.transaction.service.ServiceWithOuterTransaction;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;

import java.util.Collection;

import static com.example.demosqltest.jpa.additional.transaction.service.ServiceWithInnerRequiredNewTransaction.NESTED_TRANSACTION;
import static com.example.demosqltest.jpa.additional.transaction.service.ServiceWithOuterTransaction.TRANSACTION;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ActiveProfiles("spy6")
//@ActiveProfiles("test-containers")
@SpringBootTest
//@Sql("crate table home_entity (id int, name text)")
@Sql(statements = "truncate  home_entity")
class ServiceWithOuterTransactionTest {

    @Autowired
    ServiceWithOuterTransaction serviceWithOuterTransaction;
    @Autowired
    HomeRepository homeRepository;

    @Autowired
    HomeWithAutoGeneratedIdRepository homeWithAutoGeneratedIdRepository;


    @Test
    void notGeneratedIdEntityExcludeDouble() {
        String namePrefix = "throw-1";
        serviceWithOuterTransaction.excludeDoubleInDatabase(namePrefix);
        Collection<HomeEntity> allByName = homeRepository.findAllByName(namePrefix + TRANSACTION);
        assertEquals(1,allByName.size());
        Collection<HomeEntity> nested = homeRepository.findAllByName(namePrefix + NESTED_TRANSACTION);
        assertEquals(0,nested.size());
    }


    @Test
    void generatedAutoExcludeDoubleFalsePositive() {
        String namePrefix = "throw-1";
        serviceWithOuterTransaction.falsePositive(namePrefix);
        Collection<HomeEntityAutoGeneratedId> allByName = homeWithAutoGeneratedIdRepository.findAllByName(namePrefix + TRANSACTION);
        assertEquals(1,allByName.size());
        Collection<HomeEntityAutoGeneratedId> nested = homeWithAutoGeneratedIdRepository.findAllByName(namePrefix + NESTED_TRANSACTION);
        assertEquals(0,nested.size());
    }



    @Test
    void notGeneratedIdDeadLock() {
        String namePrefix = "throw-1";
        serviceWithOuterTransaction.deadLock(namePrefix);
        Collection<HomeEntity> allByName = homeRepository.findAllByName(namePrefix + TRANSACTION);
        assertEquals(1,allByName.size());
        Collection<HomeEntity> nested = homeRepository.findAllByName(namePrefix + NESTED_TRANSACTION);
        assertEquals(0,nested.size());
    }

}